### ISSUE TITLE
NO_SUCHFILE : Load model from /home/project/ComfyUI/models/landmarks/fan2_68_landmark.onnx failed:Load model /home/project/ComfyUI/models/landmarks/fan2_68_landmark.onnx failed. File doesn't exist

### ISSUE THREAD

**Issue by Zwl-Everett** [dchatel/comfyui_facetools#29]
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /home/project/ComfyUI/models/landmarks/fan2_68_landmark.onnx failed:Load model /home/project/ComfyUI/models/landmarks/fan2_68_landmark.onnx failed. File doesn't exist

SELECTED: input1

0: 640x448 1 person, 101.0ms
Speed: 11.7ms preprocess, 101.0ms inference, 142.7ms postprocess per image at shape (1, 3, 640, 448)

0: 1952x1280 1 face, 101.9ms
Speed: 10.7ms preprocess, 101.9ms inference, 12.8ms postprocess per image at shape (1, 3, 1952, 1280)
!!! Exception during processing !!! [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /home/project/ComfyUI/models/landmarks/fan2_68_landmark.onnx failed:Load model /home/project/ComfyUI/models/landmarks/fan2_68_landmark.onnx failed. File doesn't exist
Traceback (most recent call last):
  File "/home/project/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/project/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/project/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/project/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/project/ComfyUI/custom_nodes/comfyui_facetools/nodes.py", line 93, in run
    unfiltered_faces = detect_faces(img, threshold)
  File "/home/project/ComfyUI/custom_nodes/comfyui_facetools/utils.py", line 137, in detect_faces
    face = Face(img, a, b, c, d)
  File "/home/project/ComfyUI/custom_nodes/comfyui_facetools/utils.py", line 92, in __init__
    curr_lmk = Models.lmk(rcrop)
  File "/home/project/ComfyUI/custom_nodes/comfyui_facetools/utils.py", line 65, in lmk
    cls._lmk = InferenceSession(os.path.join(models_dir, 'landmarks', 'fan2_68_landmark.onnx'), providers=get_available_providers())
  File "/root/miniconda3/envs/comfyui/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 465, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/root/miniconda3/envs/comfyui/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 526, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /home/project/ComfyUI/models/landmarks/fan2_68_landmark.onnx failed:Load model /home/project/ComfyUI/models/landmarks/fan2_68_landmark.onnx failed. File doesn't exist

Prompt executed in 3.63 seconds
FETCH DATA from: /home/project/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/4245046894_model-list.json [DONE]
FETCH DATA from: /home/project/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/4245046894_model-list.json [DONE]
got prompt
SELECTED: input1

0: 640x448 1 face, 12.1ms
Speed: 9.7ms preprocess, 12.1ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 448)

0: 1952x1280 1 face, 16.5ms
Speed: 7.4ms preprocess, 16.5ms inference, 20.9ms postprocess per image at shape (1, 3, 1952, 1280)
!!! Exception during processing !!! [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /home/project/ComfyUI/models/landmarks/fan2_68_landmark.onnx failed:Load model /home/project/ComfyUI/models/landmarks/fan2_68_landmark.onnx failed. File doesn't exist
Traceback (most recent call last):
  File "/home/project/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/project/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/project/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

**Comment by dchatel** [comment]
![image](https://github.com/user-attachments/assets/120ea99c-227d-4aa0-a603-aa7306cb85ad)
